version: "3.9"

services:
  fastapi:
    build: .
    container_name: soil_api
    restart: always

    env_file:
      - .env

    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: cm6361
      DB_NAME: soilrecommendation

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "8000:8000"

    command: uvicorn ap:app --host 0.0.0.0 --port 8000
